services:
    redis:
        image: redis:7-alpine
        container_name: silk-fetch-redis
        restart: unless-stopped

        ports:
            - "6379:6379"

        volumes:
            - redis_data:/data

        networks:
            - silk-network

        healthcheck:
            test: "redis-cli -a ${REDIS_PASSWORD} ping"
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s
        
        command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    db:
        image: postgres:18-alpine
        container_name: silk-fetch-db
        restart: unless-stopped

        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            PGUSER: ${DB_USER}

        ports:
            - "5432:5432"

        volumes:
            - silk_postgres_data:/var/lib/postgresql/data

        healthcheck:
            test: "pg_isready -U ${DB_USER} -d ${DB_NAME}"
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

        networks:
            - silk-network
    backend:    
        build:
            context: .
            target: production
            dockerfile: backend/Dockerfile
        container_name: silk-fetch-backend
        restart: unless-stopped
        
        ports:
            - "8000:8000"

        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy

        networks:
            - silk-network
            
        env_file:
          - .env

volumes:
  silk_postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  silk-network:
    driver: bridge